# Generated by Django 2.2.2 on 2019-07-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('social cause', 'Social Cause'), ('journalism campaigns', 'Journalism Campaigns'), ('political campaigns', 'Political Campaigns')], default='social cause', max_length=50)),
                ('goal', models.IntegerField()),
                ('day', models.IntegerField()),
                ('short_description', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('campaign_image', models.ImageField(blank='True', null='True', upload_to='campaigns/images/')),
                ('is_verified', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('not active', 'Not Active'), ('deleted', 'Deleted')], default='active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capmaigns', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
