# Generated by Django 2.2.2 on 2019-07-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='raised',
            field=models.IntegerField(default=None),
        ),
    ]
