# Generated by Django 2.2.2 on 2019-07-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='raised',
            field=models.IntegerField(null=True),
        ),
    ]
