# Generated by Django 2.2.2 on 2019-07-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank='True', null='True', upload_to='EventsImg'),
        ),
    ]
